kind: Service
apiVersion: v1
metadata:
  name: kost-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: kost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kost-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: kost
  replicas: 2
  template:
    metadata:
      labels:
        app: kost
    spec:
      containers:
      - name: php-kost
        image: farman17/aplikasi-mamahkost
        ports:
          - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kost-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mamahkost.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: kost-service
          servicePort: 80

